### ISSUE TITLE
[HELP PLS] Welcome/Leave message

### ISSUE THREAD

**Issue by lilnext01** [ariffb25/stikerinbot#10]
Hai, apakah mungkin untuk mengubah nama 'Stikerin' ini? Saya ingin memasukkan nama saya, tetapi saya tidak tahu apakah itu mungkin

![Screenshot_20210719-123658_GBWhatsApp](https://user-images.githubusercontent.com/74841546/126194359-3e68ce1f-e05c-4b07-b5c7-ad4bf998ff69.jpg)

**Comment by FadliDarmawan** [comment]
> Hai, apakah mungkin untuk mengubah nama 'Stikerin' ini? Saya ingin memasukkan nama saya, tetapi saya tidak tahu apakah itu mungkin
> 
> ![Screenshot_20210719-123658_GBWhatsApp](https://user-images.githubusercontent.com/74841546/126194359-3e68ce1f-e05c-4b07-b5c7-ad4bf998ff69.jpg)

bisa, ganti saja fotonya di handler.js
