### ISSUE TITLE
ga ada cara install termux

### ISSUE THREAD

**Issue by NugrahaMP** [ariffb25/stikerinbot#100]
ini masih bisa dipake di termux kan bang?

**Comment by OPPAI-HUNTER** [comment]
Ngga

**Comment by robbyhalintar2** [comment]
Masih Bisa

**Comment by robbyhalintar2** [comment]
apt update && apt upgrade
apt install git -y
apt install nodejs -y
apt install ffmpeg -y
apt install imagemagick -y
git clone https://github.com/ariffb25/stikerinbot
cd wabot-aq
npm install
npm update

**Comment by robbyhalintar2** [comment]
> apt update && apt upgrade
> apt install git -y
> apt install nodejs -y
> apt install ffmpeg -y
> apt install imagemagick -y
> git clone https://github.com/ariffb25/stikerinbot
> cd wabot-aq
> npm install
> npm update

Nih Coba aja dulu

**Comment by OPPAI-HUNTER** [comment]
mending pake heroku

**Comment by NugrahaMP** [comment]
ga paham heroku bang

**Comment by syahrularranger** [comment]
Bukanya emng ga support termux?

**Comment by syahrularranger** [comment]
Gabakal bisa kalo di termux.. ada canvacord nya

**Comment by ariffb25** [comment]
bisa aja, instal ubuntu ditermux dulu 4gb katanya sih

**Comment by AthallahDzaki** [comment]
Closed Open Branch [termux](https://github.com/ariffb25/stikerinbot/tree/termux)
