### ISSUE TITLE
conn.sendButtonimg

### ISSUE THREAD

**Issue by Dawnfrosty** [ariffb25/stikerinbot#103]
Cara makenya gmana ya? Bisa dibantu? 
Klo aku bikin jadi kek gini terus 
`conn.sendButtonimg is not a function`
padahal dah sesuai format

> let fetch = require('node-fetch')
     let handler  = async (m, { conn, args }) => {
    heum = await fetch(`https://recoders-area.caliph.repl.co/api/loli`)
    json = await heum.buffer()
    //conn.sendFile(m.chat, json, 'loli.jpg', 'Lomlinya kak', m, false)
   conn.sendButtonimg(m.chat, json.img, 'Lomlinya kak', '© stikerin', 'NEXT', '.next')
//sendButtonImg(jid, content, url, footer, button1, row1, options = {}) {
}
handler.help = ['loli']
handler.tags = ['anime']
handler.command = /^loli$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

> handler.admin = false

> handler.botAdmin = false

> handler.fail = null

> module.exports = handler

>

**Comment by ariffb25** [comment]
https://github.com/ariffb25/stikerinbot/blob/76b21369dc5dc0a242c07803a0eea17f335e4fa6/lib/simple.js#L511-L523

contoh:
```js
await conn.sendButtonImg(m.chat, await conn.getFile(url).data, 'isi konten', 'isi footer', 'tombolnya', '.commandnya', m, { optionnya })
```
