### ISSUE TITLE
Cannot read property 'fromMe' of undefined

### ISSUE THREAD

**Issue by itsMySky** [ariffb25/stikerinbot#106]
*Mohon Solusinya Bang @ariffb25*
![Screenshot_20210829_082457](https://user-images.githubusercontent.com/80798056/131234256-62204246-7830-4b3c-a640-2829993b850f.jpg)

**Comment by ariffb25** [comment]
ntah lah, w ga eror

**Comment by jauhari21** [comment]
> _Mohon Solusinya Bang @ariffb25_
> ![Screenshot_20210829_082457](https://user-images.githubusercontent.com/80798056/131234256-62204246-7830-4b3c-a640-2829993b850f.jpg)

Semenjak ganti simple baru nih pasti,

**Comment by jauhari21** [comment]
Gua juga gitu,

**Comment by ariffb25** [comment]
pantes, jangan cuma simple.js nya aja, cek lah isinya terus sesuaikan cara pakenya
