### ISSUE TITLE
Multiperangkat

### ISSUE THREAD

**Issue by Nobuyaki** [ariffb25/stikerinbot#107]
Bang Ini Support Multipetangkat gak?

**Comment by ariffb25** [comment]
wa multi device? coba aja

**Comment by Nobuyaki** [comment]
> wa multi device? coba aja

ga support bang, biar support gimana?

**Comment by ariffb25** [comment]
> > wa multi device? coba aja
> 
> ga support bang, biar support gimana?

baileys emng blom support, yang jago2nya juga lagi nyari cara biar bisa, jadi tunggu aja di repo baileys nya
