### ISSUE TITLE
Rank card

### ISSUE THREAD

**Issue by Rizxyu** [ariffb25/stikerinbot#109]
Bang boleh add rank card command ga?

**Comment by Rizxyu** [comment]
![IMG_20210830_225400](https://user-images.githubusercontent.com/88314302/131367856-218eb27b-25cd-4687-bccf-f34a1eb8282a.png)

Kayak gingini bang

**Comment by ariffb25** [comment]
tinggal copy aja levelup.js ganti captionnya

**Comment by Rizxyu** [comment]
Ok
