### ISSUE TITLE
Tictactoe Error

### ISSUE THREAD

**Issue by Farhansaja12** [ariffb25/stikerinbot#112]
Bang Ini Knp kok gini tictactoe nya error 
![Screenshot_2021-09-06-14-15-39-213_com whatsapp](https://user-images.githubusercontent.com/88828397/132169178-02041fbe-bcc1-43c9-bba7-c6f04156565b.jpg)

**Comment by ariffb25** [comment]
{ quoted: m } ganti jadi m, soalnya ngubah func

**Comment by Farhansaja12** [comment]
> { quoted: m } ganti jadi m, soalnya ngubah func

Dimana ganti nya gw newbie

**Comment by AthallahDzaki** [comment]
fix [https://github.com/ariffb25/stikerinbot/commit/f1588cc40599506d6928ffa61c8595a5c45ec845](https://github.com/ariffb25/stikerinbot/commit/f1588cc40599506d6928ffa61c8595a5c45ec845)
