### ISSUE TITLE
Pesan Tidak Terkirim

### ISSUE THREAD

**Issue by Farhansaja12** [ariffb25/stikerinbot#113]
Solusi nya bang @ariffb25 
![IMG_20210907_062855](https://user-images.githubusercontent.com/88828397/132263594-fcea1188-b2b6-4e56-8023-4858ce5c3a0a.jpg)

**Comment by AthallahDzaki** [comment]
Whatsapp Business ya? Kalau Iya Ubah di [plugins/menu.js](https://github.com/ariffb25/stikerinbot/blob/main/plugins/menu.js) di line (Baris) [303 - 330](https://github.com/ariffb25/stikerinbot/blob/main/plugins/menu.js#L303)

**Comment by Farhansaja12** [comment]
> Whatsapp Business ya? Kalau Iya Ubah di [plugins/menu.js](https://github.com/ariffb25/stikerinbot/blob/main/plugins/menu.js) di line (Baris) hapus double slash (//) [304 - 330](https://github.com/ariffb25/stikerinbot/blob/main/plugins/menu.js#L304)

Iya Bang pke WA bisnis pas ku ilangin // ttp

**Comment by Lord-Gaming** [comment]
> Iya Bang pke WA bisnis pas ku ilangin // ttp

Wa bisnis gk support list menu
