### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by Fokusdotid** [ariffb25/stikerinbot#12]
Ngab klo error nya kek gini salahnya dmna ngab?

![Screenshot_20210723-172506966.jpg](https://user-images.githubusercontent.com/40955113/126770112-25fbbeea-21da-42ae-a1f8-4281c129ab79.jpg)

**Comment by ariffb25** [comment]
iya sama kalo instal module lewat github gabisa gitu kalo di heroku,

solusinya pake dari npm aja, bedanya blom ada button & list

**Comment by ariffb25** [comment]
@Ftwrr punya lu bisa kan?

**Comment by Fokusdotid** [comment]
pke windows boros kuota njir

**Comment by ariffb25** [comment]
di close ya karena adiwajshing udah update di npm nya jadi bisa instal baileys dari npm

**Comment by Ftwrr** [comment]
padahal ada tulisannya njirr :/
node version not specified in package.json
