### ISSUE TITLE
Redis database banggg

### ISSUE THREAD

**Issue by RidwanXyZ** [ariffb25/stikerinbot#130]
Pake database redis bang mwehehe

**Comment by Bintangp02** [comment]
prefix bot nya apa bang
?

**Comment by Bintangp02** [comment]
saya komen all prefix gak bisa bang

**Comment by RidwanXyZ** [comment]
> prefix bot nya apa bang
> ?

Multi prefix

**Comment by Hidayatilman** [comment]
> prefix bot nya apa bang
> ?

Liat di main.js global.prefix

**Comment by AthallahDzaki** [comment]
Redis Savingnya Di RAM kan?
