### ISSUE TITLE
eror handler.js

### ISSUE THREAD

**Issue by scoder37** [ariffb25/stikerinbot#146]
![Screenshot_20210927-115616](https://user-images.githubusercontent.com/90820338/134848135-7d57b189-45bf-4f83-8b75-99a62b673141.png)

**Comment by Rizxyu** [comment]
Lu apain

**Comment by scoder37** [comment]
ku hek jdi eror. org ga diapa apain cmn git clone

**Comment by syahrularranger** [comment]
Owh aku fhm
