### ISSUE TITLE
Bot tidak mereply saat button dipencet

### ISSUE THREAD

**Issue by jeffryafandi** [ariffb25/stikerinbot#155]
Saya baru mencoba bot ini kemarin, dan saat di menu "help", botnya tidak memunculkan pesan saat button ditekan, dimana itu menjadi poin minus di bot ini. tolong segera di tinjau kembali, dan melakukan "bug fixing" dengan segera. Terimakasih :)

**Comment by AthallahDzaki** [comment]
apakah anda menggunakan Whatsapp Mod?

**Comment by jeffryafandi** [comment]
> apakah anda menggunakan Whatsapp Mod?

Tidak, saya menggunakan WhatsApp original versi terbaru yang ada di google playstore.

**Comment by jeffryafandi** [comment]
Tambahan: tidak hanya pada **help** menu, hal serupa juga terjadi pada command lainnya seperti **asahotak**

**Comment by jeffryafandi** [comment]
done, problem fixed
