### ISSUE TITLE
[FEATURE?] Math buttons

### ISSUE THREAD

**Issue by lilnext01** [ariffb25/stikerinbot#16]
Apakah mungkin untuk menambahkan tombol radio di Math.js? Itu akan membantu banyak! Jika ya, dapatkah Anda membantu saya? 
terima kasih

**Comment by ariffb25** [comment]
silahkan gunakan fungsi yang sudah dibuat 
* fungsi ini untuk mengirim pesan beserta 2 tombol
https://github.com/ariffb25/stikerinbot/blob/0e7790af54f407f0524a74497bac4712cf233e9c/lib/simple.js#L281-L306
* fungsi ini untuk mengirim pesan beserta 1 tombol
https://github.com/ariffb25/stikerinbot/blob/0e7790af54f407f0524a74497bac4712cf233e9c/lib/simple.js#L226-L249
