### ISSUE TITLE
Tebak gambar & caklontong error

### ISSUE THREAD

**Issue by prioprastyo** [ariffb25/stikerinbot#17]
![IMG_20210725_221522](https://user-images.githubusercontent.com/74877180/126904165-a9e9d985-b37c-4517-bd49-d1b65d548d26.jpg)

**Comment by ariffb25** [comment]
![image](https://user-images.githubusercontent.com/76026450/126921531-e5fbed3e-0821-4b5f-a510-b195c263403e.png)
donasi bwang jangan bisa make doang :/

**Comment by prioprastyo** [comment]
Bjir:v
