### ISSUE TITLE
Setcmd

### ISSUE THREAD

**Issue by iniariaaa** [ariffb25/stikerinbot#19]
Bang, Tolong Dong Solusinya Kenapa Ya Afk Make Sticker Itu Selalu Ke Berhenti Afknya Otomatis
![Uploading Screenshot_20210727_182919.jpg…]()

**Comment by ariffb25** [comment]
gambarnya blm ke-upload itu

**Comment by iniariaaa** [comment]
belum ke upload maksudnya?

**Comment by ariffb25** [comment]
itu mau ngasih ss nya juga kan? itu blm selesai ke upload jadi gabisa dibuka

**Comment by iniariaaa** [comment]
Ok
