### ISSUE TITLE
ini kenapa bang

### ISSUE THREAD

**Issue by prioprast** [ariffb25/stikerinbot#210]
![Screenshot_2021-10-26-10-12-25-352_com termux](https://user-images.githubusercontent.com/74879576/138802818-5f339bb3-d31f-42f4-a58f-33ad737b1593.jpg)

Gua udh ngikutin caranya di deskripsi lewat termux, knp tuch bng hehe

**Comment by iamenpjordi69** [comment]
install sharp in npm
