### ISSUE TITLE
Scan Via web

### ISSUE THREAD

**Issue by ItsMeDitzzy** [ariffb25/stikerinbot#222]
Cara scan Via web url gimana bang?

**Comment by ariffb25** [comment]
di heroku? nama-app.herokuapp.com

**Comment by iamenpjordi6** [comment]
node . --big-qr not working. still giving small qr

**Comment by iamenpjordi6** [comment]
> Cara scan Via web url gimana bang?

generate session.data.json by importing repository on replit and scanning. then upload that file to github

**Comment by iamenpjordi6** [comment]
> di heroku? nama-app.herokuapp.com

cara mengaktifkan perintah admin?

**Comment by ilmanhdyt** [comment]
> > di heroku? nama-app.herokuapp.com
> 
> cara mengaktifkan perintah admin?

Baca readme
