### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by iamenpjordi6** [ariffb25/stikerinbot#229]
**Describe the bug
![Uploading Ca
![Capture](https://user-images.githubusercontent.com/90175854/140067957-aca53fd6-1bd9-46e7-a6ba-08c54065bf6d.PNG)
pture2.PNG…]()
**
Deskripsi lengkap mengenai bug

**To Reproduce**
Cara Mendapatkan Bug:

**Expected behavior**
Apa yang anda harapkan terjadi sebenarnya.

**Screenshots**
Jika bisa tambahkan gambar agar mempermudah menjelaskan bug.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Whatsapp Version : [e.g. 2.21.19.21] if using Whatsapp Mod, Type 8.22.29.3

**Additional context**
Tambahkan beberapa konteks tentang bug (Jika Perlu).

**Comment by iamenpjordi6** [comment]
how to fix this error  see screenshot

**Comment by Lord-Patrick** [comment]
> how to fix this error see screenshot

where's the screenshot? :/

**Comment by iamenpjordi6** [comment]
https://user-images.githubusercontent.com/90175854/140067957-aca53fd6-1bd9-46e7-a6ba-08c54065bf6d.PNG

**Comment by unx21** [comment]
> https://user-images.githubusercontent.com/90175854/140067957-aca53fd6-1bd9-46e7-a6ba-08c54065bf6d.PNG

are u use termux branch?

**Comment by iamenpjordi6** [comment]
> > https://user-images.githubusercontent.com/90175854/140067957-aca53fd6-1bd9-46e7-a6ba-08c54065bf6d.PNG
> 
> are u use termux branch?

i am using Amazon Lightsail VPS. Ive fixed issue by Myself now
