### ISSUE TITLE
Kesalahan baru dengan Kode QR

### ISSUE THREAD

**Issue by Bk-SaD** [ariffb25/stikerinbot#235]
Karena WhatsApp diperbarui ke Meta, saya tidak dapat memindai kode QR yang dilemparkan bot di terminal Termux atau di pc.
Jika seseorang tahu bagaimana menyelesaikannya saya akan sangat berterima kasih .. dan jika saya dapat melakukan sesuatu untuk berkontribusi saya dengan senang hati akan melakukannya .. terima kasih

**Comment by Xmell91** [comment]
change main.js

**Comment by Bk-SaD** [comment]
> cambiar main.js
ada petunjuk bahwa saya harus berubah?

**Comment by BochilGaming** [comment]
> > cambiar main.js
> > ada petunjuk bahwa saya harus berubah?

Use latest version of baileys

**Comment by iamenpjordi69** [comment]
> Use latest version of baileys
bro xteam api  expired.

**Comment by BochilGaming** [comment]
> > Use latest version of baileys
> > bro xteam api  expired.

buy apikey from api.xteam.xyz but the web is down

**Comment by MR-X-WHITEHACKER** [comment]
> > Use latest version of baileys
> > bro xteam api  expired.

> > Api tersebut belum ada mungkin, Yg ada mungkin punya Ownernya yaitu, @ariffb25

**Comment by BochilGaming** [comment]
> > > Use latest version of baileys
> > > bro xteam api  expired.
> 
> > > Api tersebut belum ada mungkin, Yg ada mungkin punya Ownernya yaitu, @ariffb25

api tersebut ada tetapi akhir akhir ini api itu mati/down

**Comment by MR-X-WHITEHACKER** [comment]
> > > Use latest version of baileys
> > > bro xteam api  expired.
> 
> > > Api tersebut belum ada mungkin, Yg ada mungkin punya Ownernya yaitu, @ariffb25


> > Aku gunakan bot, ku milih pinterest katanya,  Powered by LokupApi

**Comment by BochilGaming** [comment]
> > > > Use latest version of baileys
> > > > bro xteam api  expired.
> > 
> > 
> > > > Api tersebut belum ada mungkin, Yg ada mungkin punya Ownernya yaitu, @ariffb25
> 
> > > Aku gunakan bot, ku milih pinterest katanya,  Powered by LokupApi

ya karena pinterest gk makek api.xteam.xyz

**Comment by MR-X-WHITEHACKER** [comment]
> > > Use latest version of baileys
> > > bro xteam api  expired.
> 
> buy apikey from api.xteam.xyz but the web is down



> > > > Use latest version of baileys
> > > > bro xteam api  expired.
> > 
> > 
> > > > Api tersebut belum ada mungkin, Yg ada mungkin punya Ownernya yaitu, @ariffb25
> 
> api tersebut ada tetapi akhir akhir ini api itu mati/down

> > Owh Gitu...

**Comment by MR-X-WHITEHACKER** [comment]
Bro....

**Comment by Bk-SaD** [comment]
Nunca supe que hacer
