### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by anggita13** [ariffb25/stikerinbot#241]
Setelah mengetik node .
Muncul error seperti di gambar
![Screenshot_20211119-091817054](https://user-images.githubusercontent.com/86518199/142553709-e1497284-f9cb-4da4-9586-26c6e46ee3ac.jpg)

**Comment by ariffb25** [comment]
coba download dari npm

**Comment by anggita13** [comment]
Sudah saya coba download manual dari npm tapi tetap kak, soalnya saya kan pernah baca issue disini yang canvacord tidak support termux, tapi saya pake distro Ubuntu di termux nya bisa install canvacord, tapi saat di run jadi nya seperti itu, tetapi kalau saya tidak pakai distro Ubuntu, bisa run cuman error cannot find canvacord

**Comment by Einsteina7x** [comment]
![Screenshot_20211121-005939_Termux](https://user-images.githubusercontent.com/71550518/142749126-259fa734-7685-4b26-94bb-5a8e90594df3.jpg)
Saya tidak tahu mengapa kesalahan ini

**Comment by irwanx** [comment]
Pake heroku bisa, coba aja

**Comment by irwanx** [comment]
@Einsteina7x coba pake heroku.com

**Comment by BochilGaming** [comment]
> ![Screenshot_20211121-005939_Termux](https://user-images.githubusercontent.com/71550518/142749126-259fa734-7685-4b26-94bb-5a8e90594df3.jpg) Saya tidak tahu mengapa kesalahan ini

Jangan pakek lowdb versi terbaru

**Comment by BochilGaming** [comment]
> Setelah mengetik node . Muncul error seperti di gambar ![Screenshot_20211119-091817054](https://user-images.githubusercontent.com/86518199/142553709-e1497284-f9cb-4da4-9586-26c6e46ee3ac.jpg)

```sh
cd node_modules/@adiwajshing/baileys
npm i -g typescript
tsc
cd ../../../
node . 
```

**Comment by anggita13** [comment]
> > Setelah mengetik node . Muncul error seperti di gambar ![Screenshot_20211119-091817054](https://user-images.githubusercontent.com/86518199/142553709-e1497284-f9cb-4da4-9586-26c6e46ee3ac.jpg)
> 
> ```shell
> cd node_modules/@adiwajshing/baileys
> npm i -g typescript
> tsc
> cd ../../../
> node . 
> ```

Tetap error kak :(
![Screenshot_20211122-213317_Termux](https://user-images.githubusercontent.com/86518199/142879704-337be544-c4b3-4663-bb7a-ec7402ffa163.png)

**Comment by BochilGaming** [comment]
> > > Setelah mengetik node . Muncul error seperti di gambar ![Screenshot_20211119-091817054](https://user-images.githubusercontent.com/86518199/142553709-e1497284-f9cb-4da4-9586-26c6e46ee3ac.jpg)
> > 
> > 
> > ```shell
> > cd node_modules/@adiwajshing/baileys
> > npm i -g typescript
> > tsc
> > cd ../../../
> > node . 
> > ```
> 
> Tetap error kak :( ![Screenshot_20211122-213317_Termux](https://user-images.githubusercontent.com/86518199/142879704-337be544-c4b3-4663-bb7a-ec7402ffa163.png)

```sh
pkg upgrade && pkg update
rm -rf node_modules
npm i
```

**Comment by anggita13** [comment]
> > > > Setelah mengetik node . Muncul error seperti di gambar ![Screenshot_20211119-091817054](https://user-images.githubusercontent.com/86518199/142553709-e1497284-f9cb-4da4-9586-26c6e46ee3ac.jpg)
> > > 
> > > 
> > > ```shell
> > > cd node_modules/@adiwajshing/baileys
> > > npm i -g typescript
> > > tsc
> > > cd ../../../
> > > node . 
> > > ```
> > 
> > 
> > Tetap error kak :( ![Screenshot_20211122-213317_Termux](https://user-images.githubusercontent.com/86518199/142879704-337be544-c4b3-4663-bb7a-ec7402ffa163.png)
> 
> ```shell
> pkg upgrade && pkg update
> rm -rf node_modules
> npm i
> ```

Termux nya saya pakein ubuntu kak, soalnya kalau gak pakai Ubuntu Canvas nya gak bisa keintall, apa gara gara di Ubuntu itu ya kak, kalau ga pakai Ubuntu bisa run tapi cannot find Canvas

Sudah saya cobain install ulang 3x tetep error seperti di gambar

**Comment by BochilGaming** [comment]
npm install ulang aja coba

**Comment by anggita13** [comment]
> npm install ulang aja coba, itu error gara gara script nya gk mau anu tsc nya

Sudah 3x saya install ulang kak, hasil nya tetap

**Comment by BochilGaming** [comment]
> > npm install ulang aja coba, itu error gara gara script nya gk mau anu tsc nya
> 
> Sudah 3x saya install ulang kak, hasil nya tetap

versi npm, node, tsc berapa?

**Comment by anggita13** [comment]
> > > npm install ulang aja coba, itu error gara gara script nya gk mau anu tsc nya
> > 
> > 
> > Sudah 3x saya install ulang kak, hasil nya tetap
> 
> versi npm, node, tsc berapa?

npm versi 6.x
Node 14
tsc 4.5.2

**Comment by Einsteina7x** [comment]
> > ![Screenshot_20211121-005939_Termux](https://user-images.githubusercontent.com/71550518/142749126-259fa734-7685-4b26-94bb-5a8e90594df3.jpg) Saya tidak tahu mengapa kesalahan ini
> 
> Jangan pakek lowdb versi terbaru

Versi mana yang harus saya gunakan?

**Comment by anggita13** [comment]
> > > npm install ulang aja coba, itu error gara gara script nya gk mau anu tsc nya
> > 
> > 
> > Sudah 3x saya install ulang kak, hasil nya tetap
> 
> versi npm, node, tsc berapa?

Sudah bisa kak, habis upgrade node ke 17 & npm ke 8
![Screenshot_2021-11-24-05-29-50-107_com termux](https://user-images.githubusercontent.com/86518199/143139419-48410a7c-e184-4ee5-8abb-1e9f22246016.jpg)

**Comment by anggita13** [comment]
> > > ![Screenshot_20211121-005939_Termux](https://user-images.githubusercontent.com/71550518/142749126-259fa734-7685-4b26-94bb-5a8e90594df3.jpg) Saya tidak tahu mengapa kesalahan ini
> > 
> > 
> > Jangan pakek lowdb versi terbaru
> 
> Versi mana yang harus saya gunakan?

Install Ubuntu di termux kamu kak

**Comment by Einsteina7x** [comment]
Apakah stickerinbot memiliki alat stiker? jika ya bagaimana saya bisa menggunakan

**Comment by anggita13** [comment]
> Apakah stickerinbot memiliki alat stiker? jika ya bagaimana saya bisa menggunakan

saya memakai cara ini dan berhasil
- open termux
- command
1. pkg update && pkg upgrade
2. pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh && bash ubuntu.sh
3. ./start-ubuntu.sh
4. apt update && apt full-upgrade
5. apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev git curl 
6. curl -sL https://deb.nodesource.com/setup_17.x | bash -
7.  apt install nodejs
8. git clone https://github.com/ariffb25/stikerinbot
9. cd stikerinbot
10. npm install
11 node .

**Comment by bimaatmajaya** [comment]
> 4\. apt update && apt full-upgrade



> > Apakah stickerinbot memiliki alat stiker? jika ya bagaimana saya bisa menggunakan
> 
> saya memakai cara ini dan berhasil
> 
> * open termux
> * command
> 
> 1. pkg update && pkg upgrade
> 2. pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh && bash ubuntu.sh
> 3. ./start-ubuntu.sh
> 4. apt update && apt full-upgrade
> 5. apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev git curl
> 6. curl -sL https://deb.nodesource.com/setup_17.x | bash -
> 7. apt install nodejs
> 8. git clone https://github.com/ariffb25/stikerinbot
> 9. cd stikerinbot
> 10. npm install
>     11 node .

wah makasih banget kak tutorialnya, dan kalau boleh tau kalau mau belajar  dasarnya kira kira di mana ya kak?
