### ISSUE TITLE
Bang kok punya saya di grup muncul menu. Di chat pribadi nggk muncul menu

### ISSUE THREAD

**Issue by fafhghg1** [ariffb25/stikerinbot#248]

**Comment by Xmell91** [comment]
Coba check simple.js ada ngga?

**Comment by Xmell91** [comment]
.off gc

**Comment by fafhghg1** [comment]
ndk bisa kak

**Comment by fafhghg1** [comment]
> .off gc

nggk bisa kak

**Comment by Xmell91** [comment]
Coba ss log erornya, perasaan sya nda eror :/

**Comment by Gilbertgeraldo** [comment]
Gw kok cfonts nya error ya

**Comment by fafhghg1** [comment]
> Coba ss log erornya, perasaan sya nda eror :/

![163842947366035127035535331577](https://user-images.githubusercontent.com/94165730/144375839-e0fc673c-a1c2-4d3f-943e-8849170d1c71.jpg)
Saya make server digital ocean

**Comment by fafhghg1** [comment]
> Coba ss log erornya, perasaan sya nda eror :/

![16384295411747800308456703205269](https://user-images.githubusercontent.com/94165730/144375940-fc18ea07-64ff-4c70-9df9-90284c22dcbe.jpg)

**Comment by melcanz** [comment]
Oh databasenya eror

**Comment by melcanz** [comment]
node . --db 'https://json-server.nurutomo.repl.co/

**Comment by melcanz** [comment]
> 
Pake termux?

**Comment by melcanz** [comment]
> Gw kok cfonts nya error ya

Pake termux?

**Comment by fafhghg1** [comment]
> 

Pake server ubuntu

**Comment by melcanz** [comment]
> ubuntu

Bukan kamu v: itu ada yg nanya eror cfonts maybe dia pake termux

**Comment by fafhghg1** [comment]
> 

OOh wkwkwkwk maaf

**Comment by bimaatmajaya** [comment]
> 

permisi kak, mau tanya, sekarang udah gak bisa ya make termux?

**Comment by bimaatmajaya** [comment]
> > ubuntu
> 
> Bukan kamu v: itu ada yg nanya eror cfonts maybe dia pake termux

permisi kak, sekarang udah gak bisa make termux ya?

**Comment by melcanz** [comment]
> 



> > > ubuntu
> > 
> > 
> > Bukan kamu v: itu ada yg nanya eror cfonts maybe dia pake termux
> 
> permisi kak, sekarang udah gak bisa make termux ya?

Pake sc ku aja sama kayak stikerin udh suport termux

**Comment by melcanz** [comment]
> > 
> 
> OOh wkwkwkwk maaf

node . --db 'https://json-server.nurutomo.repl.co/

Coba run pake itu

**Comment by cahyanugraha16** [comment]
> 

Mana bang SC nya

**Comment by melcanz** [comment]
> > 
> 
> Mana bang SC nya

https://github.com/melcanz/melcanz-bot
