### ISSUE TITLE
reminder fitur bang :v

### ISSUE THREAD

**Issue by janganlahkau** [ariffb25/stikerinbot#249]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Xmell91** [comment]
Mangsud?

**Comment by ariffb25** [comment]
yg diingetin apa? w sih mending di ingetin @Xmell91 😳❤️

**Comment by melcanz** [comment]
Sapa tu

**Comment by janganlahkau** [comment]
hhhh

Pada tanggal Rab, 1 Des 2021 17.23, Amel ***@***.***> menulis:
