### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by FadliDarmawan** [ariffb25/stikerinbot#25]
![IMG-20210728-WA2062.jpeg](https://user-images.githubusercontent.com/79369935/127336115-0f40e58e-8166-4d17-bd0a-9694fce83ec5.jpeg)

How?

**Comment by ariffb25** [comment]
@Ftwrr

**Comment by ariffb25** [comment]
di close ya karena adiwajshing udah update di npm nya jadi bisa instal baileys dari npm

**Comment by Ftwrr** [comment]
telat
