### ISSUE TITLE
tolong pencerahan, perintah tidak di eksekusi oleh botnya

### ISSUE THREAD

**Issue by bimaatmajaya** [ariffb25/stikerinbot#254]
saya pengguna termux dengan server ubuntu, saya udah coba berbagai cara tapi entang mengapa perintah yang saya kirim di chat wa tidak bisa di eksekusi oleh bot walau saya sudah aktifkan on public, tolong bantuannya min
![photo_2021-12-03_16-49-37](https://user-images.githubusercontent.com/95463559/144565985-2e628802-f672-4772-bb97-b6d94f11386e.jpg)

**Comment by ariffb25** [comment]
node .

**Comment by Bintangp02** [comment]
> node .

Masih belum bisa punya ku sama kita:>
