### ISSUE TITLE
Emror

### ISSUE THREAD

**Issue by OPPAI-HUNTER** [ariffb25/stikerinbot#26]
![Screenshot_2021-07-28-21-22-24-212_com termux](https://user-images.githubusercontent.com/53190401/127339257-c5b80dc6-d4b1-40c2-9bab-27bacc6555d2.jpg)

How? pas ketik bash install.sh malah gini XD

**Comment by ariffb25** [comment]
https://github.com/Nurutomo/wabot-aq/issues/638

**Comment by ItzMeDitzzy** [comment]
> [Nurutomo/wabot-aq#638](https://github.com/Nurutomo/wabot-aq/issues/638)

Uda bisa, but menu emror 👯

**Comment by ariffb25** [comment]
update baileys kalo statusnya 400, atau jgn nyalain pesan sementara
