### ISSUE TITLE
.menu Tidak Muncul

### ISSUE THREAD

**Issue by Bintangp02** [ariffb25/stikerinbot#260]
![Screenshot_2021_1214_172300](https://user-images.githubusercontent.com/80300921/145980291-e2468e4e-7c43-4557-9b21-33a14f0d3763.jpg)

Eror Sebelum nya saya sudah install semua nya..
Saya telah mencoba dengan (node .) ,Masih saja belum bisa...

Dan ketika di telpon untuk fitur block otomatis, tidak bisa di gunakan

Masalah ini hampir sama dengan issue #254 #248

**Comment by ariffb25** [comment]
jgn pake wa bisnis
