### ISSUE TITLE
Antilink, padahal restrict udah on

### ISSUE THREAD

**Issue by Natx-C** [ariffb25/stikerinbot#265]
![Screenshot_2021-12-23-03-49-21-66](https://user-images.githubusercontent.com/83612604/147153561-9c90559b-2dcf-4ce4-b114-f367d58f66bb.jpg)
![Screenshot_2021-12-23-03-49-09-83](https://user-images.githubusercontent.com/83612604/147153569-2feb99d3-0391-4355-8c14-de15629c3b37.jpg)

**Comment by ariffb25** [comment]
admin ga dikick
