### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Naruto010** [ariffb25/stikerinbot#269]
![image](https://user-images.githubusercontent.com/87160046/147388540-bfb06ed4-f4c8-46ca-874b-423dd40e9197.jpeg)

**Comment by Natx-C** [comment]
> ![image](https://user-images.githubusercontent.com/87160046/147388540-bfb06ed4-f4c8-46ca-874b-423dd40e9197.jpeg)

Belom install ffmpeg tuh bang

**Comment by Naruto010** [comment]
> Belom install ffmpeg tuh bang

Broo lok![image](https://user-images.githubusercontent.com/87160046/147490406-250577a7-ae7d-4443-b89e-d033e25d9bc2.jpeg)
