### ISSUE TITLE
Menunggu Multi device🗿

### ISSUE THREAD

**Issue by Paquito1923** [ariffb25/stikerinbot#273]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RHns20** [comment]
sabar

**Comment by ItzLighting9332** [comment]
> pull req aj

cara ny?

**Comment by Paquito1923** [comment]
> 

Udah punya sc md
Sebagian fitur ambil punyamu

Hehe🗿

**Comment by frmdeveloper** [comment]
> Udah punya sc md Sebagian fitur ambil punyamu
> 
> Hehe🗿

Pull request lah.
Bikin brancg baru

**Comment by Paquito1923** [comment]
Hmm omke
