### ISSUE TITLE
list menu tdk bisa trkirim

### ISSUE THREAD

**Issue by muhammadzakizn** [ariffb25/stikerinbot#277]
![8e71907c-24f7-4568-8816-392ee079737c](https://user-images.githubusercontent.com/73261827/148880152-8d4e96ed-0f43-4938-ab47-981b0c448cb6.jpg)
?help, list menu ny g terkirim, udh coba bbrp kali, ttp gitu
please solution..

**Comment by ariffb25** [comment]
jgn pake wa bisnis
