### ISSUE TITLE
Adakah yang tahu cara menonaktifkan autoread?

### ISSUE THREAD

**Issue by Bk-SaD** [ariffb25/stikerinbot#288]
Adakah yang tahu cara menonaktifkan autoread?

**Comment by Lord-Patrick** [comment]
.off autoread

**Comment by Paquito1923** [comment]
> Adakah yang tahu cara menonaktifkan autoread?

edit di handler.js, autoread jadiin false
atau ketik aja .off autoread

**Comment by Bk-SaD** [comment]
Thanks everyone..
