### ISSUE TITLE
YouTube Error Bang

### ISSUE THREAD

**Issue by Mx-Shimmer-01** [ariffb25/stikerinbot#299]
![Screenshot_20220209_111234_com anwhatsapp](https://user-images.githubusercontent.com/89338571/153120590-0cd30245-cbea-4015-9eab-02b3c42e1d62.jpg)

Error

**Comment by ariffb25** [comment]
tinggal disable aja SSL sertificate nya, bisa taro di `main.js` paling atas
```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```

**Comment by Mx-Shimmer-01** [comment]
Ok tq work dah bisa:) btw fitur jadi bit sama admin emang gabisa ya?

Pada tanggal Kam, 10 Feb 2022 07:43, ariffb ***@***.***>
menulis:
