### ISSUE TITLE
Btw cara ubah gambar di menu gimana bang?

### ISSUE THREAD

**Issue by Mx-Shimmer-01** [ariffb25/stikerinbot#304]
![Screenshot_20220212_072837_com anwhatsapp](https://user-images.githubusercontent.com/89338571/153688092-4b05a818-1bc7-4622-b27f-bdcf7c5d8940.jpg)

Yang Tulisannya Owner Tuh di ganti sama anime gimana bro?

**Comment by Mx-Shimmer-01** [comment]
Ada yang tau?

**Comment by Paquito1923** [comment]
> Ada yang tau?

ganti aja fla + text dengan url gambar mu

di menu.js

**Comment by Mx-Shimmer-01** [comment]
Oke tq

Pada tanggal Min, 13 Feb 2022 12:18, Elyas ***@***.***>
menulis:

**Comment by Mx-Shimmer-01** [comment]
> > Ada yang tau?
> 
> ganti aja fla + text dengan url gambar mu
> 
> di menu.js

Error bro

**Comment by zevanoo** [comment]
> Ada yang tau?

ganti aja global.fla di config.js pake url mu sendiri dan di menu.js kan ad tu 'fla + text' cb text ny lu apus

**Comment by Mx-Shimmer-01** [comment]
Gabisa v

Pada tanggal Min, 13 Feb 2022 14:00, Zevano Albarsabit <
***@***.***> menulis:
