### ISSUE TITLE
Cannot find modul 'cfond'

### ISSUE THREAD

**Issue by bimaatmajaya** [ariffb25/stikerinbot#307]
![Screenshot_2022-02-16-16-08-22-511_com termux](https://user-images.githubusercontent.com/95463559/154214324-a33fd5ec-9c97-469d-8a46-c5409893c304.jpg)

Ini solusinya gimana ya bang

**Comment by ariffb25** [comment]
npm i

**Comment by botstylee** [comment]
> ![Screenshot_2022-02-16-16-08-22-511_com termux](https://user-images.githubusercontent.com/95463559/154214324-a33fd5ec-9c97-469d-8a46-c5409893c304.jpg)
> 
> Ini solusinya gimana ya bang

npm i cfonts
