### ISSUE TITLE
Npm i

### ISSUE THREAD

**Issue by namzahran01** [ariffb25/stikerinbot#309]
![Screenshot_Termux_20220221-192124](https://user-images.githubusercontent.com/43334234/154960609-c42b3f4a-ef8b-43a5-9587-b1589566489b.png)
why is my npm install like this?

**Comment by botstylee** [comment]
> ![Screenshot_Termux_20220221-192124](https://user-images.githubusercontent.com/43334234/154960609-c42b3f4a-ef8b-43a5-9587-b1589566489b.png) why is my npm install like this?

npm install -g npm@6.14.14
