### ISSUE TITLE
TOD Game

### ISSUE THREAD

**Issue by rockleeghost** [ariffb25/stikerinbot#34]
Bang, kan ada truth or dare, nah dibuat  versi acak bang, pakai button sekalian hehe.
Misal ada 3 button {Truth, Dare, Acak} gitu dh pokoknya

**Comment by FadliDarmawan** [comment]
> Bang, kan ada truth or dare, nah dibuat versi acak bang, pakai button sekalian hehe.
> Misal ada 3 button {Truth, Dare, Acak} gitu dh pokoknya

menarik

**Comment by Ftwrr** [comment]
udah tuh

**Comment by ariffb25** [comment]
udah
