### ISSUE TITLE
Cara Agar Bio Otomatis Terubah

### ISSUE THREAD

**Issue by arskyganzz** [ariffb25/stikerinbot#35]
Bang Ajarin Saya Cara Agar Bio Terubah Secara Otomatis Sesuai Runtime/Uptime

**Comment by ariffb25** [comment]
kan udah dibuat begitu :/ https://github.com/ariffb25/stikerinbot/blob/main/plugins/_autorespon.js

**Comment by oneechan123** [comment]
> kan udah dibuat begitu :/ https://github.com/ariffb25/stikerinbot/blob/main/plugins/_autorespon.js

Klo mau diubah jadi database user gimana?

**Comment by arskyganzz** [comment]
> Bang Ajarin Saya Cara Agar Bio Terubah Secara Otomatis Sesuai Runtime/Uptime

**Comment by ariffb25** [comment]
> > kan udah dibuat begitu :/ https://github.com/ariffb25/stikerinbot/blob/main/plugins/_autorespon.js
> 
> Klo mau diubah jadi database user gimana?

```JS
Object.keys(global.db.data.users).length
```
