### ISSUE TITLE
Gk bisa node .

### ISSUE THREAD

**Issue by oneechan123** [ariffb25/stikerinbot#38]
![IMG-20210730-WA0582](https://user-images.githubusercontent.com/73242335/127738151-113c9de3-4d43-4e4a-b9dd-abd7e2027688.jpg)

Gimana cara benerinya bang?

**Comment by OPPAI-HUNTER** [comment]
> ![IMG-20210730-WA0582](https://user-images.githubusercontent.com/73242335/127738151-113c9de3-4d43-4e4a-b9dd-abd7e2027688.jpg)
> 
> Gimana cara benerinya bang?

Update Baileys

**Comment by ariffb25** [comment]
jgn pake yarn

**Comment by oneechan123** [comment]
> jgn pake yarn

Pake apa trus bang?

**Comment by ariffb25** [comment]
closed, karena skrng pake canva jd termux kyknya gabisa
