### ISSUE TITLE
List messages

### ISSUE THREAD

**Issue by FadliDarmawan** [ariffb25/stikerinbot#40]
Cara biar list messages bisa di respon sebagai command

**Comment by ariffb25** [comment]
dari awal udh bisa tinggal buat aja, commandnya taroh dlm selectedRowId 

https://github.com/ariffb25/stikerinbot/blob/16fa8221828bbdf94150e11b5f243afc5bb267b3/lib/simple.js#L582

**Comment by FadliDarmawan** [comment]
> dari awal udh bisa tinggal buat aja, commandnya taroh dlm selectedRowId 
> 
> https://github.com/ariffb25/stikerinbot/blob/16fa8221828bbdf94150e11b5f243afc5bb267b3/lib/simple.js#L582

Terimakasih bang
