### ISSUE TITLE
Tebak Gambar ga bisa hint

### ISSUE THREAD

**Issue by jauhari21** [ariffb25/stikerinbot#41]
![Screenshot_2021-08-01-04-54-46-75](https://user-images.githubusercontent.com/81492529/127753229-8b772ab5-5117-4818-ad2e-6a4904dd1b6f.jpg)

**Comment by ariffb25** [comment]
![Screenshot_2021-08-01-06-17-28-713_com whatsapp](https://user-images.githubusercontent.com/76026450/127754490-5155fdc0-a40f-4162-acd1-e8a615e4d814.jpg)
bisa kok, gantengnya ilang sih:v

**Comment by jauhari21** [comment]
Udah bisa xixixi simple.jsnya belum diganti
