### ISSUE TITLE
[BUG] Anti Delete

### ISSUE THREAD

**Issue by ariffb25** [ariffb25/stikerinbot#42]
Sebelum beberapa pembaharuan ahkir-akhir ini, event message-delete tidak bekerja sebagaimana mestinya :/ sebelumnya masih bisa & di log ada, sedangkan user yang jadibot antideletenya bisa

Kalo tau dimana salahnya pull req ya TwT

**Comment by amiruldev20** [comment]
sampai skrg blm bsa ya?

**Comment by botkus** [comment]
coba npm update 
terus hapus session.data,json
terus npm i 
npm update lagi 

terus jalankan bot secara normal ...

terus coba .off delete .. 

Aku coba kaya gitu bisa soalnya

**Comment by botkus** [comment]
> coba npm update
> terus hapus session.data,json
> terus npm i
> npm update lagi
> 
> terus jalankan bot secara normal ...
> 
> terus coba .off delete ..
> 
> Aku coba kaya gitu bisa soalnya

Ini buat yang delete ... kalo anti call gtw

**Comment by AthallahDzaki** [comment]
Please Check My [Pull Request](https://github.com/ariffb25/stikerinbot/pull/95)
