### ISSUE TITLE
Expiration

### ISSUE THREAD

**Issue by jauhari21** [ariffb25/stikerinbot#44]
![Screenshot_2021-08-02-04-14-20-67](https://user-images.githubusercontent.com/81492529/127785575-0233a8e6-2759-4f4f-8f8f-1b25e2f1d261.jpg)

**Comment by ariffb25** [comment]
biarin aja, itu buat detect kalo ephemeral nyala

**Comment by jauhari21** [comment]
> biarin aja, itu buat detect kalo ephemeral nyala

Tapi jadi ga ngebales chat orang ,

**Comment by jauhari21** [comment]
Eh udah bisa xixixi
