### ISSUE TITLE
Kok gini?

### ISSUE THREAD

**Issue by oneechan123** [ariffb25/stikerinbot#49]
![IMG_20210802_175911](https://user-images.githubusercontent.com/73242335/127851458-f32e8c89-eb60-479e-b4a0-5ef47ac214cf.jpg)

Ini kenapa bang?
Cara benerinya gimana?

**Comment by OPPAI-HUNTER** [comment]
update baileys?

**Comment by ariffb25** [comment]
itu jaringan kalo statusnya 422
