### ISSUE TITLE
Caranya agar tulisan nya muat bagaimana? Atau memperkecil ukuran teks agar muat juga :/

### ISSUE THREAD

**Issue by prioprastyo** [ariffb25/stikerinbot#5]

**Comment by prioprastyo** [comment]
![IMG_20210715_222005](https://user-images.githubusercontent.com/74877180/125813459-fd6c97c3-3a86-4c06-91e3-b3ab6a77a85a.jpg)

**Comment by ariffb25** [comment]
itu dari rest api nya begitu suka ganti2 si Hardianto
