### ISSUE TITLE
[REQUEST] ButtonImg in Profile

### ISSUE THREAD

**Issue by lilnext01** [ariffb25/stikerinbot#52]
Apakah mungkin menambahkan tombol ke .profile.js? Saya mencoba menambahkan tetapi ada kesalahan

**Comment by ariffb25** [comment]
tentu,

### 1. mengubah isi variabel ```pp```
```js
let pp = 'https://telegra.ph/file/b097856a96d89154955dc.png'
```
### 2. gunakan fungsi berikut
```js
await conn.sendButtonImg(m.chat, str, pp, '', 'MY', ',my')
```
tutup issue ini jika sudah selesai

**Comment by lilnext01** [comment]
> tentu,
> 
> ### 1. mengubah isi variabel `pp`
> ```js
> let pp = 'https://telegra.ph/file/b097856a96d89154955dc.png'
> ```
> 
> ### 2. gunakan fungsi berikut
> ```js
> await conn.sendButtonImg(m.chat, str, pp, '', 'MY', ',my')
> ```
> 
> tutup issue ini jika sudah selesai

Thkss  <3
