### ISSUE TITLE
Tombol tod ga bisa di klik dan fix family100 tombol

### ISSUE THREAD

**Issue by jauhari21** [ariffb25/stikerinbot#54]
![Screenshot_2021-08-04-16-19-45-93](https://user-images.githubusercontent.com/81492529/128156318-9233aaaf-4bf9-4822-a0c3-22a3c2f502a2.jpg)

Oh iya family100_answer ada yg typo tuh tulisannya koma bukan titik. Jadi tombolnya ga bisa dipencet saat mau main family100 lg

**Comment by ariffb25** [comment]
pasti ngga ngikutin update :/ soalnya udh nambah koma di ```main.js```

**Comment by OPPAI-HUNTER** [comment]
![IMG_20210804_162957](https://user-images.githubusercontent.com/53190401/128157783-e94050fd-82c3-4657-822c-a452fee98b1c.jpg)


Sy bisa, Keknya lu ga teliti:v

**Comment by jauhari21** [comment]
> ![IMG_20210804_162957](https://user-images.githubusercontent.com/53190401/128157783-e94050fd-82c3-4657-822c-a452fee98b1c.jpg)
> 
> Sy bisa, Keknya lu ga teliti:v

Ya maap bang
