### ISSUE TITLE
Baileys Error

### ISSUE THREAD

**Issue by russellraders** [ariffb25/stikerinbot#55]
![IMG_20210804_213528](https://user-images.githubusercontent.com/79731052/128205430-f693e0ef-7ddb-4e39-8937-e207fe4e886e.jpg)
Ini knapa ya? Ini udah gunain baileys terbaru

**Comment by ariffb25** [comment]
install baileysnya dari githubnya bukan?

**Comment by russellraders** [comment]
> install baileysnya dari githubnya bukan? 

Iyaa, dari github

**Comment by ariffb25** [comment]
versi wa? pesan sementara nyala?

**Comment by russellraders** [comment]
Udah bisa bang. Mungkin karna tadi pake wa beta, sekarang ganti pake wa bussines

**Comment by russellraders** [comment]
Thank you
