### ISSUE TITLE
Tolong saya

### ISSUE THREAD

**Issue by prioprast** [ariffb25/stikerinbot#57]
![IMG_20210805_011757](https://user-images.githubusercontent.com/74879576/128233628-62b40147-6ba5-45da-ba73-8745e2e73b78.jpg)

Udah npm i & bash install.sh masih nggak bisa,
Waktu aku coba tadi hapus node_modules terus npm i lagi hasilnya tetap sama saja.

Kira-kira masalah apa yang harus saya lakukan untuk membuatnya tidak seperti itu?

Terima kasih

**Comment by prioprast** [comment]
![IMG_20210805_013626](https://user-images.githubusercontent.com/74879576/128236033-2f6c0805-2bc9-417f-a11b-6bd4b3fe3f05.jpg)

Dan aku juga mendapatkan masalah yang seperti ini

**Comment by prioprast** [comment]
Itu membuat sebagian fitur menghilang

**Comment by ariffb25** [comment]
I'm recommended use RDP/PC
