### ISSUE TITLE
Bikin sticker harus di reply?

### ISSUE THREAD

**Issue by oneechan123** [ariffb25/stikerinbot#59]
![Screenshot_2021-08-05-11-55-30-53_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/73242335/128297193-eb09aa44-1b44-4930-9570-44a05e81d412.jpg)

Setiap bikin sticker pake caption gini mulu, apa harus di reply?

**Comment by ariffb25** [comment]
itu gagal upload ke telegraph nya, coba ganti pake imgbb
