### ISSUE TITLE
Req buggc,bugtroli,bug hode om..

### ISSUE THREAD

**Issue by ZeusFtrOfc** [ariffb25/stikerinbot#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by prioprastyo** [comment]
Ntar ke block lho nomor WhatsApp nya, kaya punya aku yg satunya keblock hm...

Sumpah nyesel bat adain begituan wkwk

**Comment by ZeusFtrOfc** [comment]
:(( ,iyaa" om:(

Pada tanggal 18 Jul 2021 11:00, "TiTiT gede" ***@***.***>
menulis:

**Comment by EaBro** [comment]
Self Bot? cek profile [Disini](github.com/eabro/xselfbot) @ZeusFtrOfc @prioprastyo 

`:v`

**Comment by botstylee** [comment]
Lagi pula buat apa nyari bug begitu gak guna kalo cumang bersenang senang spam ke orang yg gak bersalah, gw aja yg punya buggc troli biasa aja paling cumang ngecek ngecek doang masih work apa kagak kalo masih work gw anggurin

**Comment by EaBro** [comment]
> Lagi pula buat apa nyari bug begitu gak guna kalo cumang bersenang senang spam ke orang yg gak bersalah, gw aja yg punya buggc troli biasa aja paling cumang ngecek ngecek doang masih work apa kagak kalo masih work gw anggurin

Wkwk
