### ISSUE TITLE
[FEATURE] Waiting time in TicTacToe 

### ISSUE THREAD

**Issue by lilnext01** [ariffb25/stikerinbot#62]
Bagaimana dengan menambahkan Batas Tunggu di Tic-Tac-Toe? beberapa pengguna menjalankan perintah, tetapi jika menghabiskan beberapa waktu dan tidak bermain (karena itu AFK) Kemudian, pengguna lain dipaksa untuk menyerah. 

akan bekerja seperti ini: 
Pengguna memiliki 1 menit untuk bergerak, jika waktu habis, kemenangan akan diberikan kepada Pemain lain. 

itu semuanya.

**Comment by Rizxyu** [comment]
Uh

**Comment by Rizxyu** [comment]
Bisa bang kalo lu set time out,
Terus kasih juga delete conn.game

**Comment by ariffb25** [comment]
> Bisa bang kalo lu set time out,
> Terus kasih juga delete conn.game

pull req aja
