### ISSUE TITLE
Ganti Api caklontong dah koid

### ISSUE THREAD

**Issue by jauhari21** [ariffb25/stikerinbot#64]
Cobain ganti gan 
https://api.zeks.xyz/api/cak-lontong?apikey=apivinz

**Comment by ariffb25** [comment]
nanti gaperlu api lagi kok

**Comment by ariffb25** [comment]
https://github.com/ariffb25/stikerinbot/tree/b9a190a5b0b98b2642c379d8c2ba1e1567b01620

**Comment by jauhari21** [comment]
Mantab
