### ISSUE TITLE
Bikin sticker eror

### ISSUE THREAD

**Issue by oneechan123** [ariffb25/stikerinbot#66]
![Screenshot_2021-08-08-22-36-40-09_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/73242335/128637587-f7f141c7-8893-4318-a6a9-bdcf8b376f40.jpg)
Cara benerinya?, Padahal dh di reply tapi malah disuruh reply sama bot

**Comment by ariffb25** [comment]
coba gambar yg direply
