### ISSUE TITLE
Send Image/Gif form local to Sticker

### ISSUE THREAD

**Issue by arh-space** [ariffb25/stikerinbot#69]
Mau nanya, cara kirim image/gif dari local jadi sticker gimana ya? kek fitur pikachu.js, terima kasih yang mau jawab

**Comment by ariffb25** [comment]
```js
conn.sendFile(m.chat, './src/file.gif', 'file.gif', 'ini caption', m, 0, { mimetype: 'video/gif' })
```

**Comment by arh-space** [comment]
> ```js
> conn.sendFile(m.chat, './src/file.gif', 'file.gif', 'ini caption', m, 0, { mimetype: 'video/gif' })
> ```

Maksud nya nanti pas ngirim dari local result nya menjadi sticker gan, gimana ya?

**Comment by ariffb25** [comment]
```js
conn.sendFile(m.chat, './src/file.gif', 'file.gif', 'ini caption', m, 0, { asSticker: true })
```
atau
```js
conn.sendMessage(m.chat, fs.readFileSync('./src/file.gif'), MessageType.sticker, { mimetype: Mimetype.webp })
```
baca sendiri dokumentasinya [disini](https://adiwajshing.github.io/Baileys/)

**Comment by arh-space** [comment]
> ```js
> m, 0, { asSticker: true })
> ```

thanks gan, akhirnya bisa dari tadi sticker nya blank pake kek gini baru bisa

conn.sendFile(m.chat, fs.readFileSync('./src/pika.gif'), MessageType.video, '', m, 0, { asSticker: true })

**Comment by ariffb25** [comment]
sip
