### ISSUE TITLE
Mau Tanya 

### ISSUE THREAD

**Issue by botkus** [ariffb25/stikerinbot#72]
Kalo misalnya habis klik button ... misal kayak ytmp4 .... waktu diklik keluar tulisan masukkan Link gitu ... terus tinggal di kirim ...

jadi semuanya ga ngetik gitu ... cuma mencet terus kirim wkwkwk

**Comment by ariffb25** [comment]
masukan link berarti ngetik dong :/

**Comment by botkus** [comment]
> masukan link berarti ngetik dong :/

Iya... setelah diklik terus kirim link lansung si konversi

**Comment by ariffb25** [comment]
kan udh
