### ISSUE TITLE
Semua Button

### ISSUE THREAD

**Issue by botkus** [ariffb25/stikerinbot#73]
Biar semua button dalam satu pesan gmn?

**Comment by ariffb25** [comment]
coba jelasin detailnya gmn? sy bukan dukun

**Comment by amiruldev20** [comment]
mungkin maksudnya semua menu itu di button jdi ga susah" ketik

**Comment by botkus** [comment]
> mungkin maksudnya semua menu itu di button jdi ga susah" ketik

Iya ... tinggal klik gitu wkaokwoa

**Comment by ariffb25** [comment]
sedangkan button maksimalnya hanya 3

**Comment by botkus** [comment]
> sedangkan button maksimalnya hanya 3, kalo mau pake listMessage buat sendiri :/

caranya?

**Comment by ariffb25** [comment]
https://adiwajshing.github.io/Baileys/#non-media-messages 
```js
// send a list message!
const rows = [
 {title: 'Row 1', description: "Hello it's description 1", rowId:"rowid1"},
 {title: 'Row 2', description: "Hello it's description 2", rowId:"rowid2"}
]

const sections = [{title: "Section 1", rows: rows}]

const button = {
 buttonText: 'Click Me!',
 description: "Hello it's list message",
 sections: sections,
 listType: 1
}

const sendMsg = await conn.sendMessage(id, button, MessageType.listMessage)
```

**Comment by botkus** [comment]
hmm

taruh di?

**Comment by ariffb25** [comment]
menu.js

**Comment by botkus** [comment]
contoh in

**Comment by botkus** [comment]
ga ngerti aku

**Comment by ariffb25** [comment]
kalo ga ngerti dari situ ya belajar :/

**Comment by botkus** [comment]
nanti kalo dipencet kok ga keluar apa apa?

**Comment by botkus** [comment]
> kalo ga ngerti dari situ ya belajar :/

caranya biar dipencet langsung keluar perintah gmn?

**Comment by botkus** [comment]
> https://adiwajshing.github.io/Baileys/#non-media-messages
> 
> ```js
> // send a list message!
> const rows = [
>  {title: 'Row 1', description: "Hello it's description 1", rowId:"rowid1"},
>  {title: 'Row 2', description: "Hello it's description 2", rowId:"rowid2"}
> ]
> 
> const sections = [{title: "Section 1", rows: rows}]
> 
> const button = {
>  buttonText: 'Click Me!',
>  description: "Hello it's list message",
>  sections: sections,
>  listType: 1
> }
> 
> const sendMsg = await conn.sendMessage(id, button, MessageType.listMessage)
> ```

title nya di ganti sama commandnya kah?

**Comment by ariffb25** [comment]
rowId yg isinya perintah

**Comment by botkus** [comment]
owh  oke

**Comment by botkus** [comment]
support sama wa bisnis ga? dulu pernah dicoba ga support

**Comment by botkus** [comment]
> https://adiwajshing.github.io/Baileys/#non-media-messages
> 
> ```js
> // send a list message!
> const rows = [
>  {title: 'Row 1', description: "Hello it's description 1", rowId:"rowid1"},
>  {title: 'Row 2', description: "Hello it's description 2", rowId:"rowid2"}
> ]
> 
> const sections = [{title: "Section 1", rows: rows}]
> 
> const button = {
>  buttonText: 'Click Me!',
>  description: "Hello it's list message",
>  sections: sections,
>  listType: 1
> }
> 
> const sendMsg = await conn.sendMessage(id, button, MessageType.listMessage)
> ```

MessageType.listMessage di isi apa?

**Comment by botkus** [comment]
![image](https://user-images.githubusercontent.com/88307305/129300288-595fd851-6017-4bb0-b811-e23a55d4657b.png)
Hasilnya error

**Comment by ariffb25** [comment]
> support sama wa bisnis ga? dulu pernah dicoba ga support

ngga

**Comment by ariffb25** [comment]
https://github.com/ariffb25/stikerinbot/commit/c786815fa046668e785016ecf8e5344e8c8118e1
