### ISSUE TITLE
Reply Pesan

### ISSUE THREAD

**Issue by botkus** [ariffb25/stikerinbot#76]
caranya gmn kalo kayak gini

Kita : #attp         
Bot : Reply Pesan ini dengan text yang akan di konversi

Terus kita reply 
> Bot : Reply Pesan ini dengan text yang akan di konversi

Kita : Budi ...

nanti bot otomatis kirim stiker attp dengan text BUDI

dari reply gitu bukan kayak #attp budi 

Butuh bangettt

**Comment by ariffb25** [comment]
jadi perlu 2 file kalo kek gini
1. ubah file ```attp.js```
```js
const fetch = require('node-fetch')
const { sticker } = require('../lib/sticker')
const { MessageType } = require('@adiwajshing/baileys')

let handler = async (m, { conn, text, command }) => {
  throw `#attp - animation text to picture

balas pesan ini untuk membuat attp`
}
handler.help = ['attp <teks>']
handler.tags = ['sticker']

handler.command = /^attp$/i

module.exports = handler
```
2. membuat file baru ```attp_.js```
```js
let handler = m => m
handler.before = async function (m, { conn }) {
    if (!m.quoted || !m.quoted.fromMe || !m.quoted.isBaileys || !/balas pesan ini untuk membuat attp/i.test(m.quoted.text)) return !0
    conn.sendFile(m.chat, global.API('xteam', '/attp', { file: '', text: m.text }), 'attp.webp', '', m, false, { asSticker: true })
}
module.exports = handler
```

**Comment by botkus** [comment]
Kasih kayak conn.attp gitu biar gantian konversi nya kk 

jadi kalo ada yang belum selesai konversi keluar 'Tunggu masih ada yang melakukan konversi di chat ini !!'

Terus kasih timeout 10 detik ... biar yang lain bisa. ..



> jadi perlu 2 file kalo kek gini
> 
> 1. ubah file `attp.js`
> 
> ```js
> const fetch = require('node-fetch')
> const { sticker } = require('../lib/sticker')
> const { MessageType } = require('@adiwajshing/baileys')
> 
> let handler = async (m, { conn, text, command }) => {
>   throw `#attp - animation text to picture
> 
> balas pesan ini untuk membuat attp`
> }
> handler.help = ['attp <teks>']
> handler.tags = ['sticker']
> 
> handler.command = /^attp$/i
> 
> module.exports = handler
> ```
> 
> 1. membuat file baru `attp_.js`
> 
> ```js
> let handler = m => m
> handler.before = async function (m, { conn }) {
>     if (!m.quoted || !m.quoted.fromMe || !m.quoted.isBaileys || !/balas pesan ini untuk membuat attp/i.test(m.quoted.text)) return !0
>     conn.sendFile(m.chat, global.API('xteam', '/attp', { file: '', text: m.text }), 'attp.webp', '', m, false, { asSticker: true })
> }
> module.exports = handler
> ```

**Comment by ariffb25** [comment]
buat sendiri, kan udah ada contohnya
