### ISSUE TITLE
antilink error

### ISSUE THREAD

**Issue by alvi1909** [ariffb25/stikerinbot#77]
antilink error mas, tolong di fix ya 🙏 jika ada waktu. makasih maaf jika merepotkN

**Comment by ariffb25** [comment]
sertakan pesan erornya, saya bukan dukun

**Comment by alvi1909** [comment]
> sertakan pesan erornya, saya bukan dukun

itu dia pak, disini gk ad tulisan errorny di cmd pun juga. .on antilink udh saya nyalain .enable antilink jg gk work

**Comment by ariffb25** [comment]
> > sertakan pesan erornya, saya bukan dukun
> 
> itu dia pak, disini gk ad tulisan errorny di cmd pun juga. .on antilink udh saya nyalain .enable antilink jg gk work

saat run ngetiknya ini
```bash
node . --restrict
```

**Comment by alvi1909** [comment]
> > > sertakan pesan erornya, saya bukan dukun
> > 
> > 
> > itu dia pak, disini gk ad tulisan errorny di cmd pun juga. .on antilink udh saya nyalain .enable antilink jg gk work
> 
> saat run ngetiknya ini
> 
> ```shell
> node . --restrict
> ```

ttp aja bang gbs, coba deh

**Comment by prioprast** [comment]
if (!opts['restrict']) if (plugin.tags && plugin.tags.includes('admin')) continue

Coba hapus tanda admin nya atau kosongkan aja ngab

**Comment by alvi1909** [comment]
> if (!opts['restrict']) if (plugin.tags && plugin.tags.includes('admin')) continue
> 
> Coba hapus tanda admin nya atau kosongkan aja ngab, di handler.js

tetep gk  bs ngab

**Comment by ariffb25** [comment]
typo sy 🗿 dibagian ```enable.js``` harusnya antiLink

**Comment by ariffb25** [comment]
gmn udh bisa?

**Comment by alvi1909** [comment]
> gmn udh bisa?

Udh broo, mksih bnyk🙏
