### ISSUE TITLE
Expired

### ISSUE THREAD

**Issue by oneechan123** [ariffb25/stikerinbot#79]
![IMG_20210815_171926](https://user-images.githubusercontent.com/73242335/129475196-a31feec4-073f-49c1-b24e-8e875ad219b2.jpg)
Cara ngubah ke 30hari gimana? Tanpa ngetik .expired 30, soalnya banyak grupnya klo ngetik .expired 30 kesetiap grup pasti makan waktu banyak

**Comment by ariffb25** [comment]
kalo minus gitu, ngga terbatas sbnrnya, jadi ngga bakal keluar gc

**Comment by oneechan123** [comment]
> kalo minus gitu, ngga terbatas sbnrnya, jadi ngga bakal keluar gc

Klo dibikin terbatas gimana contohnya cuma 30hari, nanti klo botnya dh 30hari berada di gc bakalan otomatis keluar

**Comment by syahrularranger** [comment]
> > kalo minus gitu, ngga terbatas sbnrnya, jadi ngga bakal keluar gc
> 
> Klo dibikin terbatas gimana contohnya cuma 30hari, nanti klo botnya dh 30hari berada di gc bakalan otomatis keluar

expired = new Date() * 1 * 86400000 * 30

**Comment by oneechan123** [comment]
> > > kalo minus gitu, ngga terbatas sbnrnya, jadi ngga bakal keluar gc
> > 
> > 
> > Klo dibikin terbatas gimana contohnya cuma 30hari, nanti klo botnya dh 30hari berada di gc bakalan otomatis keluar
> 
> expired = new Date() * 1 + 86400000 * 30

Ditambah

**Comment by oneechan123** [comment]
> > > kalo minus gitu, ngga terbatas sbnrnya, jadi ngga bakal keluar gc
> > 
> > 
> > Klo dibikin terbatas gimana contohnya cuma 30hari, nanti klo botnya dh 30hari berada di gc bakalan otomatis keluar
> 
> expired = new Date() * 1 + 86400000 * 30

Ditambah kemana?
