### ISSUE TITLE
[HELP PLS] lockCmdWithMedia error\?

### ISSUE THREAD

**Issue by lilnext01** [ariffb25/stikerinbot#8]
Bagaimana cara menggunakan "LockCmdWithMedia" dengan benar? Saya tidak mengerti, ini berfungsi untuk mencegah pengguna lain menggunakan perintah stempel itu jika "dikunci", dan hanya Penulis yang dapat menggunakannya, bukan? tetapi, dengan saya itu tidak berfungsi, saya memblokir, dan semua pengguna masih menggunakan secara normal, dapatkah Anda membantu saya ??

**Comment by ariffb25** [comment]
locking it means it can't be deleted by the user, it can only be deleted by the owner

menguncinya berarti tidak bisa dihapus oleh user, hanya bisa dihapus oleh Owner

**Comment by lilnext01** [comment]
> locking it means it can't be deleted by the user, it can only be deleted by the owner
> 
> menguncinya berarti tidak bisa dihapus oleh user, hanya bisa dihapus oleh Owner

Mengerti, saya pikir itu akan memblokir, dan hanya siapa pun yang memblokirnya yang dapat menggunakannya (bagaimanapun juga, itu akan menjadi ide yang bagus 💡 ) bukan? terima kasih banyak untuk menjawab saya!
