### ISSUE TITLE
QR Code not loading in heroku

### ISSUE THREAD

**Issue by manishkumar1601** [ariffb25/stikerinbot#80]
![image](https://user-images.githubusercontent.com/76832269/129480363-bc3517c6-1898-4f7c-8fac-983a96f874fb.png)

**Comment by ariffb25** [comment]
use another way.
- scan first in local
- push it to ur private github
- and deploy to heroku

**Comment by manishkumar1601** [comment]
please can you make a tutorial video to deploy on heroku it will be easy to understand for all bot users

**Comment by OPPAI-HUNTER** [comment]
try using node . --server in terminal heroku

**Comment by bilal-08** [comment]
> use another way.
> 
> * scan first in local
> * push it to ur private github
> * and deploy to heroku

the other is that you can login to your terminal and termux and Tail the logs in real time
