### ISSUE TITLE
Auto Upsw

### ISSUE THREAD

**Issue by itsMySky** [ariffb25/stikerinbot#82]
Hallo Bang, Kenapa Yah Setiap Ada Orang Hapus Sw, Bot Langsung Mengirim Otomatis Sw Itu Ke Sw Bot.Dan Juga Yang Jadi Bot Hpus Sw Kekirim Otomatis Juga

Adakah Cara Mematikannya?

Makasih
@ariffb25

**Comment by ariffb25** [comment]
karena antideletenya ku aktifkan
hapus database.json, kemudian ubah menjadi true
https://github.com/ariffb25/stikerinbot/blob/2ba3574c8378fc60814efa2ea9423ed1d77a817d/handler.js#L80
https://github.com/ariffb25/stikerinbot/blob/2ba3574c8378fc60814efa2ea9423ed1d77a817d/handler.js#L94

atau gunakan
```
=> db.data.chats['status@broadcast'].delete = true
```

**Comment by itsMySky** [comment]
> karena antideletenya ku aktifkan
> hapus database.json, kemudian ubah menjadi true
> https://github.com/ariffb25/stikerinbot/blob/2ba3574c8378fc60814efa2ea9423ed1d77a817d/handler.js#L80
> 
> 
> https://github.com/ariffb25/stikerinbot/blob/2ba3574c8378fc60814efa2ea9423ed1d77a817d/handler.js#L94
> 
> atau gunakan
> 
> ```
> => db.data.chats['status@broadcast'].delete = true
> ```

Makasih Bang
