### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by FadliDarmawan** [ariffb25/stikerinbot#83]
Menu ga muncul (listmessages) di wa bisnis

**Comment by OPPAI-HUNTER** [comment]
coba pke wa ori

**Comment by ariffb25** [comment]
listMessage blm bisa di wa bisnis, di menu.js kan ada yg dikomentarin tuh, pake yg itu
https://github.com/ariffb25/stikerinbot/blob/2ba3574c8378fc60814efa2ea9423ed1d77a817d/plugins/menu.js#L246-L272

**Comment by FadliDarmawan** [comment]
> coba pke wa ori

Whatsapp messanger biasa?

**Comment by FadliDarmawan** [comment]
> listMessage blm bisa di wa bisnis, di menu.js kan ada yg dikomentarin tuh, pake yg itu
> https://github.com/ariffb25/stikerinbot/blob/2ba3574c8378fc60814efa2ea9423ed1d77a817d/plugins/menu.js#L246-L272

Ok

**Comment by OPPAI-HUNTER** [comment]
> > coba pke wa ori
> 
> Whatsapp messanger biasa?

Yoi
