### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by FadliDarmawan** [ariffb25/stikerinbot#87]
kita tau fitur #play itu pake button
nah send button message yang ada image nya ga bisa di pesan sementara

bisa engga kalau pesan sementara nya nyala dia bakal send pesan biasa bukan button, kalau pesan sementara nya mati pake button....

**Comment by ariffb25** [comment]
lagi dibuat biar bisa dipesan sementara

**Comment by ariffb25** [comment]
done pake location
