### ISSUE TITLE
Helep 

### ISSUE THREAD

**Issue by alvi1909** [ariffb25/stikerinbot#88]
Autodownload nyala sendiri, cara matiinnya gmn ya mint :/

**Comment by ariffb25** [comment]
banchat aja

**Comment by alvi1909** [comment]
> banchat aja

Kalo antidelete gmn? Yg command 1 grup yg kebuka semua chat sm grup

**Comment by ariffb25** [comment]
otomatis nyala diawal chat, kalo mau off di awal, hapus database.json
ubah jadi true
https://github.com/ariffb25/stikerinbot/blob/8a003b3d7153e8cca484c9a22f6fc27bc6b7bdc6/handler.js#L80
https://github.com/ariffb25/stikerinbot/blob/8a003b3d7153e8cca484c9a22f6fc27bc6b7bdc6/handler.js#L94

**Comment by syahrularranger** [comment]
> > banchat aja
> 
> Kalo antidelete gmn? Yg command 1 grup yg kebuka semua chat sm grup

Pke exec di chat aja 
```js
> let chat = Object.keys(global.db.data.chats)

for (let id of chat) {
global.db.data.chats[id].delete = true
}
```
