### ISSUE TITLE
Apa perbedaannya

### ISSUE THREAD

**Issue by oneechan123** [ariffb25/stikerinbot#89]
Apa bedanya "handler.rowner = true" dengan "handler.owner = true"

**Comment by ariffb25** [comment]
https://github.com/ariffb25/stikerinbot/blob/8a003b3d7153e8cca484c9a22f6fc27bc6b7bdc6/handler.js#L153-L154

isROwner = pengguna yang scan jadibot + nomor yang ada di global.owner
isOwner = isROwner + nomor yang dijadikan bot
