### ISSUE TITLE
Nyalain fitur admin

### ISSUE THREAD

**Issue by oneechan123** [ariffb25/stikerinbot#93]
Cara nyalahin fitur admin gimana?

**Comment by ariffb25** [comment]
```node . --restrict```

**Comment by Lord-Gaming** [comment]
> `node . --restrict`

Gk bisa bang

**Comment by ariffb25** [comment]
hapus aja baris ini
https://github.com/ariffb25/stikerinbot/blob/8a003b3d7153e8cca484c9a22f6fc27bc6b7bdc6/handler.js#L169
