### ISSUE TITLE
Ditaro dimana?

### ISSUE THREAD

**Issue by oneechan123** [ariffb25/stikerinbot#97]
expired = new Date() * 1 + 86400000 * 30

Ini ditaro dibagian mana?, Kemarin dh nanya tapi kepencet close issue nya

**Comment by ariffb25** [comment]
handler.js

**Comment by oneechan123** [comment]
> handler.js

Dibagian mana?

**Comment by ariffb25** [comment]
https://github.com/ariffb25/stikerinbot/blob/d9c7db3c5c73ef80726457e2fd1cd2acbffdce32/handler.js#L83
https://github.com/ariffb25/stikerinbot/blob/d9c7db3c5c73ef80726457e2fd1cd2acbffdce32/handler.js#L96
