### ISSUE TITLE
Play.JS | Server Eror

### ISSUE THREAD

**Issue by robbyhalintar2** [ariffb25/stikerinbot#99]
Server id4 error!
Server en60 error!
mencoba server lain...
Server en61 error!
mencoba server lain...
Server en68 error!
mencoba server lain...
semua server gagal

#Tolong Di Perbaiki

**Comment by ariffb25** [comment]
kalo server eror bukan urusan sy, tinggal ganti pake rest api/scrape yg lain

**Comment by robbyhalintar2** [comment]
> kalo server eror bukan urusan sy, tinggal ganti pake rest api/scrape yg lain

Owh Oke Kak

**Comment by robbyhalintar2** [comment]
> kalo server eror bukan urusan sy, tinggal ganti pake rest api/scrape yg lain

Ada Update Lagi Kah Kak ?

**Comment by ariffb25** [comment]
gada

**Comment by robbyhalintar2** [comment]
> kalo server eror bukan urusan sy, tinggal ganti pake rest api/scrape yg lain

Bang Gimana cara nya ??

**Comment by ariffb25** [comment]
ganti aja pake api ini https://neoxr-api.herokuapp.com/docs udah ada diconfig tinggal pake

**Comment by robbyhalintar2** [comment]
> ganti aja pake api ini https://neoxr-api.herokuapp.com/docs udah ada diconfig tinggal pake

itu nantik ganti nya di mana ??
